version: '3.9'

services:
  datadb:
    logging:
      driver: "none"
    build:
      dockerfile: Dockerfile.mysql
      context: .
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: quidax-go
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - ./data/mysql:/var/lib/mysql
  app:
    build:
      dockerfile: Dockerfile.tigerbeetle
    # command: start --addresses=repl1.docker.internal:3000,repl2.docker.internal:3001,repl3.docker.internal:3002 /data/quidax_01.tigerbeetle
    restart: always
    ports:
      - '3000:3000'
      - '55059:8080'
    environment:
      - CGO_ENABLED=1
      - DATA_DB_URL=datadb:3306
      - TX_DB_URL=127.0.0.1:3000
    cap_add:    
      - IPC_LOCK
    volumes:
      - ./data/tigerbeetle:/db/data
    security_opt:
      - "seccomp=unconfined"
    privileged: true
    depends_on:
      - datadb
    # hostname: repl1.docker.internal
